Initial import into develop

diff --git a/templates/awx.template b/templates/awx.template
--- a/templates/awx.template
+++ b/templates/awx.template
@@ -29,7 +29,7 @@ Parameters:
     Type: String
     Default: removeme
   AWXTaskRegistry:
-    Description: Name of ECR containing the awx_task image
+    Description: Name of ECR containing the awx_task 
     Type: String
     Default: removeme
   RabbitMQRegistry:
@@ -60,8 +60,25 @@ Parameters:
     Description: Master database Username. Only applicable if DatabaseEndpoint is
       blank
     Type: String
+  AWXAdminPassword:
+    Description: Password for the AWX admin user. Required
+      is blank
+    Type: String
+    NoEcho: 'true'
+  AWXAdminUsername:
+    Description: AWX Admin user name
+    Type: String
+    Default: admin
   DatabaseEndpoint:
     Description: Endpoint for postgres database
+    Type: String
+    Default: removeme
+  ALBARN:
+    Description: Arn for ALB
+    Type: String
+    Default: removeme
+  VPC:
+    Description: VPCID
     Type: String
     Default: removeme
 Conditions:
@@ -119,6 +136,7 @@ Resources:
                 Action:
                   - ecr:GetAuthorizationToken
   AWXCodeBuildProject:
+    DependsOn: CodeBuildRole
     Type: AWS::CodeBuild::Project
     Properties:
       Name: !Sub 'awx-build-${AWS::StackName}'
@@ -130,7 +148,7 @@ Resources:
         Type: LINUX_CONTAINER
         ComputeType: BUILD_GENERAL1_SMALL
         Image: docker.io/amazonlinux:2017.09
-        PrivilegedMode: true
+        PrivilegedMode: True
         EnvironmentVariables:
           - Name: AWX_TASK_REPO
             Value: !Ref 'AWXTaskRegistry'
@@ -140,6 +158,26 @@ Resources:
             Value: !Ref 'MemcachedRegistry'
           - Name: RABBITMQ_REPO
             Value: !Ref 'RabbitMQRegistry'
+          - Name: AWX_VERSION
+            Value: !Ref 'AWXVersion'
+          - Name: pg_hostname
+            Value: !Ref 'DatabaseEndpoint'
+          - Name: pg_password
+            Value: !Ref MasterUserPassword
+          - Name: pg_username
+            Value: !Ref MasterUsername
+          - Name: awx_username
+            Value: !Ref AWXAdminUsername
+          - Name: awx_password
+            Value: !Ref AWXAdminPassword
+          - Name: cfn_signal_url
+            Value: 'placeholder'
+          - Name: cfn_stack_id
+            Value: 'placeholder'
+          - Name: cfn_logical_resource_id
+            Value: 'placeholder'
+          - Name: cfn_request_id
+            Value: 'placeholder'
       Source:
         Auth:
           Type: OAUTH
@@ -150,25 +188,285 @@ Resources:
           phases:
             install:
               commands:
-                - yum install -y git gcc docker python27-pip python27-devel libffi-devel openssl-devel git
+                - yum install -y git gcc docker python27-pip python27-devel libffi-devel openssl-devel git curl util-linux
                 - /usr/bin/pip install -U docker-py ansible awscli
                 - service docker start
                 - $(aws ecr get-login --no-include-email)
+                - set
             build:
               commands:
                 - cd installer/
-                - ansible-playbook -i inventory install.yml
-                - ACCOUNT_ID=$(echo ${CODEBUILD_BUILD_ARN} | awk '{print $4}')
+                - echo ansible-playbook -i inventory -e pg_hostname=$pg_hostname,pg_username=$pg_username,pg_password=$pg_password,pg_database=awx,pg_port=5432,default_admin_user="$awx_username",default_admin_password="$awx_password" install.yml
+                - ansible-playbook -i inventory -e pg_hostname="$pg_hostname",pg_username="$pg_username",pg_password="$pg_password",pg_database="awx",pg_port="5432",default_admin_user="$awx_username",default_admin_password="$awx_password" install.yml
+                - docker container ls --all
+                - docker image ls --all
+                - export ACCOUNT_ID=$(echo ${CODEBUILD_BUILD_ARN} | awk -F':' '{print $5}')
                 - >
-                  docker tag awx_task ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_TASK_REPO} &&
-                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_TASK_REPO}
+                  docker tag ansible/awx_task ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_TASK_REPO}:${AWX_VERSION} &&
+                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_TASK_REPO}:${AWX_VERSION}
                 - >
-                  docker tag awx_web ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_WEB_REPO} &&
-                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_WEB_REPO}
+                  docker tag ansible/awx_web ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_WEB_REPO}:${AWX_VERSION} &&
+                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${AWX_WEB_REPO}:${AWX_VERSION}
                 - >
-                  docker tag memcached ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MEMCACHED_REPO} &&
-                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MEMCACHED_REPO}
+                  docker tag memcached:alpine ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MEMCACHED_REPO}:${AWX_VERSION} &&
+                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${MEMCACHED_REPO}:${AWX_VERSION}
                 - >
-                  docker tag rabbitmq ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${RABBITMQ_REPO} &&
-                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${RABBITMQ_REPO}
+                  docker tag rabbitmq:3 ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${RABBITMQ_REPO}:${AWX_VERSION} &&
+                  docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${RABBITMQ_REPO}:${AWX_VERSION}
+            post_build:
+              commands:
+                # FIXME: Need to trap and only execute this if the Build is passing.
+                - echo "Signal back if we have gotten this far"
+                # FIXME: Wanted to add a UUID but then I have an issue with storing these somewhere.
+                - export UUID=1233244324
+                - |
+                  if [ $CODEBUILD_BUILD_SUCCEEDING -eq 1 ]
+                  then
+                    curl -X PUT -H 'Content-Type:' -d "{\"StackId\":\"$cfn_stack_id\", \"RequestId\":\"$cfn_request_id\", \"LogicalResourceId\":\"$cfn_logical_resource_id\", \"PhysicalResourceId\":\"$UUID\", \"Status\":\"SUCCESS\"}" "$cfn_signal_url"
+                  else
+                    curl -X PUT -H 'Content-Type:' -d "{\"StackId\":\"$cfn_stack_id\", \"RequestId\":\"$cfn_request_id\", \"LogicalResourceId\":\"$cfn_logical_resource_id\", \"PhysicalResourceId\":\"$UUID\", \"Status\":\"FAILED\"}" "$cfn_signal_url"
+                  fi
+      # FIXME: get this close to the actual time things take with 5 minute margin added for safety
       TimeoutInMinutes: 60
+  BuildContainers:
+    Type: Custom::BuildContainers
+    Properties:
+      # FIXME: This is to force a build, increment number (should only be the versions of AWX that cause this.)
+      UpdateMe: 931
+      ServiceToken: !GetAtt BuildContainersLambda.Arn
+      BuildProjectName: !Ref AWXCodeBuildProject
+      # cfn_signal_url: is part of the event by default hence missing here 
+      # cfn_stack_id: is part of the event by default 
+      # cfn_request_id: also part of the event
+      # cfn_logical_resource_id: also part of the event
+      # Lambda function passes the above into the build project when invoking StartBuild
+  BuildContainersLambda:
+    DependsOn: BuildContainersLambdaExecutionRole
+    Type: AWS::Lambda::Function
+    Properties:
+      Code:
+        S3Bucket: !Ref QSS3BucketName
+        S3Key: 
+          Fn::Join:
+            - ""
+            - - !Ref QSS3KeyPrefix
+              - "scripts/lambda_codebuild.zip"
+      Handler: !Sub "lambda_codebuild.lambda_handler"
+      Runtime: python2.7
+      Timeout: 300
+      Role: !GetAtt BuildContainersLambdaExecutionRole.Arn
+  BuildContainersLambdaExecutionRole:
+    Type: AWS::IAM::Role
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: '2012-10-17'
+        Statement:
+        - Effect: Allow
+          Principal:
+            Service:
+            - lambda.amazonaws.com
+          Action:
+          - sts:AssumeRole
+      Path: "/"
+      Policies:
+      - PolicyName: root
+        PolicyDocument:
+          Version: '2012-10-17'
+          Statement:
+          - Effect: Allow
+            Action:
+            - codebuild:StartBuild
+            Resource: !GetAtt AWXCodeBuildProject.Arn
+  ECSServiceRole:
+    Type: AWS::IAM::Role
+    Properties:
+      Path: /
+      AssumeRolePolicyDocument:
+        Statement:
+          - Action: sts:AssumeRole
+            Effect: Allow
+            Principal:
+              Service: ecs.amazonaws.com
+      Policies:
+        - PolicyName: ecs-service
+          PolicyDocument:
+            Statement:
+              - Effect: Allow
+                Action:
+                  - ec2:AuthorizeSecurityGroupIngres
+                  - ec2:Describe*
+                  - elasticloadbalancing:DeregisterInstancesFromLoadBalancer
+                  - elasticloadbalancing:DeregisterTargets
+                  - elasticloadbalancing:Describe*
+                  - elasticloadbalancing:RegisterInstancesWithLoadBalancer
+                  - elasticloadbalancing:RegisterTargets
+                Resource: '*'
+  AWXWebService:
+    Type: AWS::ECS::Service
+    DependsOn: ListenerRule
+    Properties:
+      Cluster: !Ref Cluster
+      Role: !Ref ECSServiceRole
+      DesiredCount: 1
+      TaskDefinition: !Ref AWXWebTaskDefinition
+      LoadBalancers:
+        - ContainerName: !Ref AWXWebRegistry
+          ContainerPort: 8052
+          TargetGroupArn: !Ref TargetGroup 
+  AWXWebTaskDefinition:
+    Type: AWS::ECS::TaskDefinition
+    Properties:
+      ContainerDefinitions:
+        - Name: !Ref AWXWebRegistry
+          Hostname: awxweb
+          Essential: true
+          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AWXWebRegistry}:${AWXVersion}
+          Memory: 1024
+          PortMappings:
+            - ContainerPort: 8052
+              HostPort: 80
+          LogConfiguration:
+            LogDriver: json-file
+          Environment:
+            - Name: "http_proxy"
+              Value: ""
+            - Name: "https_proxy"
+              Value: ""
+            - Name: no_proxy
+              Value: ""
+            - Name: SECRET_KEY
+              Value: "awxsecret"
+            - Name: DATABASE_NAME
+              Value: "awx"
+            - Name: DATABASE_USER
+              Value: !Ref MasterUsername
+            - Name: DATABASE_PASSWORD
+              Value: !Ref MasterUserPassword
+            - Name: DATABASE_PORT
+              Value: "5432"
+            - Name: DATABASE_HOST
+              Value: !Ref 'DatabaseEndpoint'
+            - Name: RABBITMQ_USER
+              Value: "guest"
+            - Name: RABBITMQ_PASSWORD
+              Value: "guest"
+            - Name: RABBITMQ_HOST
+              Value: "rabbitmq"
+            - Name: RABBITMQ_PORT
+              Value: "5672"
+            - Name: RABBITMQ_VHOST
+              Value: "awx"
+            - Name: MEMCACHED_HOST
+              Value: "memcached"
+            - Name: MEMCACHED_PORT
+              Value: "11211"
+            - Name: AWX_ADMIN_USER
+              Value: !Ref AWXAdminUsername
+            - Name: AWX_ADMIN_PASSWORD
+              Value: !Ref AWXAdminPassword
+        - Name: !Ref RabbitMQRegistry
+          Hostname: rabbitmq
+          Essential: true
+          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${RabbitMQRegistry}:${AWXVersion}
+          Memory: 1024
+          PortMappings:
+            - ContainerPort: 4369
+          LogConfiguration:
+            LogDriver: json-file
+        - Name: !Ref AWXTaskRegistry
+          Hostname: awx
+          Essential: true
+          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AWXTaskRegistry}:${AWXVersion}
+          Memory: 2048
+          PortMappings:
+            - ContainerPort: 8052
+          LogConfiguration:
+            LogDriver: json-file
+          Environment:
+            - Name: "http_proxy"
+              Value: ""
+            - Name: "https_proxy"
+              Value: ""
+            - Name: no_proxy
+              Value: ""
+            - Name: SECRET_KEY
+              Value: "awxsecret"
+            - Name: DATABASE_NAME
+              Value: "awx"
+            - Name: DATABASE_USER
+              Value: !Ref MasterUsername
+            - Name: DATABASE_PASSWORD
+              Value: !Ref MasterUserPassword
+            - Name: DATABASE_PORT
+              Value: "5432"
+            - Name: DATABASE_HOST
+              Value: !Ref 'DatabaseEndpoint'
+            - Name: RABBITMQ_USER
+              Value: "guest"
+            - Name: RABBITMQ_PASSWORD
+              Value: "guest"
+            - Name: RABBITMQ_HOST
+              Value: "rabbitmq"
+            - Name: RABBITMQ_PORT
+              Value: "5672"
+            - Name: RABBITMQ_VHOST
+              Value: "awx"
+            - Name: MEMCACHED_HOST
+              Value: "memcached"
+            - Name: MEMCACHED_PORT
+              Value: "11211"
+            - Name: AWX_ADMIN_USER
+              Value: !Ref AWXAdminUsername
+            - Name: AWX_ADMIN_PASSWORD
+              Value: !Ref AWXAdminPassword
+        - Name: !Ref MemcachedRegistry
+          Hostname: memcached
+          Essential: true
+          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${MemcachedRegistry}:${AWXVersion}
+          Memory: 2048
+          PortMappings:
+            - ContainerPort: 11211
+          LogConfiguration:
+            LogDriver: json-file
+
+  TargetGroup:
+    Type: AWS::ElasticLoadBalancingV2::TargetGroup
+    Properties:
+      VpcId: !Ref VPC
+      Port: 80
+      Protocol: HTTP
+      Matcher: 
+        HttpCode: 200-499
+      HealthCheckIntervalSeconds: 10
+      HealthCheckPath: /
+      HealthCheckProtocol: HTTP
+      HealthCheckTimeoutSeconds: 5
+      HealthyThresholdCount: 2
+  ListenerRule:
+    Type: AWS::ElasticLoadBalancingV2::ListenerRule
+    Properties:
+      ListenerArn: !Ref Listener
+      Priority: 1
+      Conditions:
+      - Field: path-pattern
+        Values:
+        - "/"
+      Actions:
+      - Type: forward
+        TargetGroupArn: 
+          Ref: TargetGroup
+  Listener:
+    Type: AWS::ElasticLoadBalancingV2::Listener
+    DependsOn: BuildContainers
+    Properties:
+      DefaultActions:
+      - Type: forward
+        TargetGroupArn: !Ref 'TargetGroup'
+      LoadBalancerArn: !Ref 'ALBARN'
+      Port: '80'
+      Protocol: HTTP
+# Container port info
+# Web 80
+# Task 8052
+# RabbitMQ 4369
+# Memcache 11211
